Minimum characters option for streaming.
SillyTavern/Extension-Speech-Recognition pull request #11
Opened 2024-08-21 23:12 UTC by madmoogle

Added an option for a minimum number of characters to be detected before a transcript is sent in order to prevent errant detections triggering responses.

2024-08-21 23:13 UTC, madmoogle commented
First time contributing to a github project, apologies for any missteps in etiquette.

2024-08-22 10:46 UTC, Cohee1207 commented on streaming.js
> +		triggerCharMin: 1,
For backwards compatibility, the default state should disabled

2024-08-22 10:47 UTC, Cohee1207 commented on streaming.js
> +		if (data.transcript.length > this.settings.triggerCharMin) {
You need to check that the `this.settings.triggerCharMin` is non-zero, otherwise it is impossible to disable.

2024-08-22 10:48 UTC, Cohee1207 commented on streaming.js
> +		this.settings.triggerCharMin = $('#speech_recognition_streaming_trigger_min_chars').val();
Convert the input value to number via `parseInt()` or `Number()`, otherwise it will be recorded as a string.

2024-08-22 10:48 UTC, Cohee1207 commented on streaming.js
> +		<span>Minimum spoken characters to trigger</span><br>\
We prefer 4 spaces instead of tabs.

2024-08-22 10:49 UTC, Cohee1207 requested changes
Left some comments.

2024-08-22 14:37 UTC, madmoogle commented on streaming.js
> +		if (data.transcript.length > this.settings.triggerCharMin) {
I'm unsure what you mean by this, > 0 allows all inputs effectively disabling it.

2024-08-22 17:16 UTC, merged